### ISSUE TITLE
No data when unknown error happens on API call

### ISSUE THREAD

**Issue by krymen** [Bandwidth/node-messaging#3]
SDK returns no data in error object when API fails for unknown reason (eg. connection reset). Error object looks as follows:
```javascript
{
   errorCode: null    
   errorMessage: "HTTP Response Not OK"    
   errorResponse: null 
}
```

This happened to us yesterday (2020-06-03) and we have no idea what was happening on the Bandwidth end.

**Comment by hamermike** [comment]
I apologize for our delay in reaching out but due to the length of time since the issue was reported I'm going to close it out. Please don't hesitate to reach out if the issue persists.

**Comment by krymen** [comment]
@hamermike We've given up using the SDK. We find it immature in regards to how it handles edge cases like the aforementioned one. Our app (https://waitwhile.com/) heavily relies on messaging and we need to know all the details about all the errors happening there.

**Comment by hamermike** [comment]
Thank you for taking the time to respond, it's extremely helpful in letting us know where to prioritize our work. I'll share this with the team and we'll work to make improvements.
